CREATE TABLE MISPARTIDOS (_ID INTEGER PRIMARY KEY AUTOINCREMENT,LIGA INTEGER,CATEGORIA INTEGER,EQUIPO1,EQUIPO2,FECHA,LUGAR,NOTIFICAR INTEGER NOT NULL DEFAULT 1);
INSERT INTO MISPARTIDOS (_ID,LIGA,CATEGORIA,EQUIPO1,EQUIPO2,FECHA,LUGAR,NOTIFICAR) VALUES (1,1,2,"VIEJITOSa","VIEJITOSb","2017-1-20","LA CAPILLITA",1);
INSERT INTO MISPARTIDOS (_ID,LIGA,CATEGORIA,EQUIPO1,EQUIPO2,FECHA,LUGAR,NOTIFICAR) VALUES (2,1,2,"SEMIVIEJa","SEMIVIEJb","2017-1-21","LA CAPILLITA",1);
INSERT INTO MISPARTIDOS (_ID,LIGA,CATEGORIA,EQUIPO1,EQUIPO2,FECHA,LUGAR,NOTIFICAR) VALUES (3,1,2,"ADULTOSa","ADULTOSb","2017-1-22","LA CAPILLITA",1);
INSERT INTO MISPARTIDOS (_ID,LIGA,CATEGORIA,EQUIPO1,EQUIPO2,FECHA,LUGAR,NOTIFICAR) VALUES (4,1,2,"JOVENESa","JOVENESb","2017-1-23","CHAPINO",1);
INSERT INTO MISPARTIDOS (_ID,LIGA,CATEGORIA,EQUIPO1,EQUIPO2,FECHA,LUGAR,NOTIFICAR) VALUES (5,1,2,"NENESa","NENESb","2017-1-24","CHAPINO",1);


